### PR TITLE
fix: errors

### LINKED ISSUE #3: Cannot open file internal error
https://connection.keboola.com/admin/utils/logs?file=2018/05/09/14/2018-05-09-14-28-20-5af2e9644f29e-exception

https://keboola.zendesk.com/agent/tickets/8370

Vypadá to že by ho to mělo proiterovat jako sliced soubor ale místo toho ho to otevírá napřímo.

### PR DESCRIPTION
**Pull request by ondrejhlavacek**
- stack trace on app exceptions
- user exception when a folder inside a sliced file exists
- app exceptions to stderr
- FIXES #3

### CODE REVIEW

File: main.php [hunk 1]
```diff
@@ -95,6 +102,7 @@
     echo $e->getMessage();
     exit(1);
 } catch (\Exception $e) {
-    echo $e->getMessage();
+    echo $e->getMessage() . PHP_EOL;
```
Comment (odinuv) [inline main.php]: stderr

**Review by odinuv — APPROVED** [review]
